name: Release Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'campux/**'
      - '.github/workflows/build-latest-image.yaml'
      - 'main.py'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Registry
      run: docker login --username=${{ secrets.DOCKER_HUB_USERNAME }} --password ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Create Buildx
      run: docker buildx create --name mybuilder --use
    - name: Build
      run: docker buildx build --platform linux/arm64,linux/amd64 -t rockchin/campuxbot:latest . --push

    - name: Push Finish Notification
      run: |
        curl --location '${{ secrets.ONEBOT_V11_ENDPOINT }}/send_group_msg' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ secrets.ONEBOT_V11_TOKEN }}' \
          --data '{
              "group_id": ${{ secrets.ONEBOT_V11_GROUP_ID }},
              "message": "CampuxBot 构建完成。"
          }'